debug: false

spring:
  datasource:
    initialize: true

coo:
  druid:
    #url: jdbc:mysql://localhost:3306/coo?autoReconnect=true&characterEncoding=UTF-8&useSSL=true
    #username: root
    #password: root
    maxActive: 20
    minIdle: 5
    initialSize: 5
    filters: stat,slf4j
  hibernate:
    #dialect: org.hibernate.dialect.MySQL5Dialect
    #showSql: true
  task:
    executorPoolSize: 5